---
title: Governance
author: SCiP
date: '2021-06-20'
slug: governance
url: /governance/
showDate: false
---

### President and Directorship

- President: Pietro Cipresso, University of Turin
- President-Elect: Laura Allen, University of New Hampshire
- Executive Director: Erin Buchanan, Harrisburg University
- Executive Director: Rick Dale, UCLA

### Steering Committee

- 2018-2021: Stephanie Huette, The University of Memphis
- 2018-2021: Kay Livesay, Linfield College
- 2021-2024: Xiaowei Zhao, Emmanuel College
- 2021-2024: Caitlin Mills, University of New Hampshire
- 2022-2025: Ulf-Dietrich Reips, University of Konstanz
- 2022-2025: Brendan Johns, McGill University 

[Click here for SCiP's bylaws](https://docs.google.com/document/d/1lM7udTN3c8P17Xx5mkf6xChUIKabMR2y8Ibz2qfQbNk/edit)

### Past Presidents

- 2020: Alexandra Paxton, University of Connecticut
- 2019: Danielle McNamara, Arizona State University
- 2018: Chris Westbury, University of Alberta
- 2017: Xiaowei Zhao, Emmanuel College
- 2016: Randy Jamieson, University of Manitoba
- 2015: Peter Dixon, University of Alberta
- 2014: Kay Livesay, Linfield College
- 2013: Michael Jones, Indiana University
- 2012: Ping Li, Pennsylvania State University 
- 2011: Joseph P. Magliano, Northern Illinois University
- 2010: Michael H. Birnbaum, California State University, Fullerton 
- 2009: Xiangen Hu, The University of Memphis
- 2008: Gary L. Bradshaw, Mississippi State University
- 2007: Roman Taraban, Texas Tech University
- 2006: Ulf-Dietrich Reips, University of Zürich 
- 2005: Christopher Wolfe, Miami University, Oxford 
- 2004: Robert Proctor, Purdue University 
- 2003: Curt Burgess, University of California, Riverside
- 2002: David Washburn, Georgia State University 
- 2001: Sarah Ransdell, Florida Atlantic University 
- 2000: Walter Beagley, Alma College 
- 1999: John Krantz, Hanover College 
- 1998: Douglas Eamon, University of Wisconsin-Whitewater 
- 1997: Margaret Anderson, State University of New York 
- 1996: Michael Levy, University of Florida 
- 1995: William Palya, Jacksonville State University 
- 1994: Paula Goolkasian, University of North Carolina, Charlotte 
- 1993: Doris Aaronson, New York University 
- 1992: Darrell Butler, Ball State University 
- 1991: Jonathan Vaughan, Carnegie-Mellon University
- 1990: David Eckerman, University of North Carolina 
- 1989: Cynthia McDaniel, Northern Kentucky University 
- 1988: Earl Hunt, University of Washington 
- 1987: Cynthia Null, College of William and Mary 
- 1986: Walter Schneider, University of Illinois 
- 1985: Dominic Massaro, University of California, Santa Cruz 
- 1984: Geoffrey Loftus, University of Washington
- 1983: Alan Lesgold, University of Pittsburgh
- 1982: Russell Church, Brown University 
- 1981: John Cotton, University of California, Santa Barbara 
- 1980: N. John Castellan, Indiana University
- 1979: Daniel Bailey, University of Colorado 
- 1978: Richard Millward, Brown University 
- 1977: Peter Polson, University of Colorado Boulder
- 1976: Lee Gregg, Carnegie-Mellon University
- 1975: Joseph Sidowski, University of South Florida
- 1974: William Uttal, University of Michigan
- 1973: Donald Tepas, Saint Louis University
- 1972: Donald Tepas, Saint Louis University

### Past Steering Committee

- 2018-2020: Erin Buchanan, Harrisburg University
- 2017-2020: Laura Allen, University of New Hampshire
- 2017-2020: Blair Armstrong, University of Toronto
- 2017-2020: Pietro Cipresso, University of Turin
- 2016-2019: Alexandra Paxton, University of Connecticut
- 2016-2019: Brendan Johns, University at Buffalo
- 2016-2019: Danielle McNamara, Arizona State University
- 2015-2018: Stefan Stieger, U. Konstanz
- 2015-2018: Carol Connor, Arizona State University
- 2015-2018: Ulf-Dietrich Reips, University of Konstanz
- 2014-2017: Jennifer Trueblood, Vanderbilt University
- 2014-2017: Matthew Crump, Brooklyn College of CUNY
- 2014-2017: Stephanie Huette, The University of Memphis
- 2013-2016: Jon Willits, Indiana University
- 2013-2016: Scott Crossley, Georgia State University
- 2013-2016: Chris Westbury, University of Alberta
- 2013-2016: Todd Gureckis, New York University
- 2012-2015: Monica Riordan, Chatham University
- 2012-2015: Zhiqiang (Carl) Cai, University of Memphis
- 2011-2014: Chris Koch, George Fox University
- 2011-2014: Ulf-Dietrich Reips, University of Konstanz
- 2010-2013: Xiaowei Zhao, Emmanuel College
- 2010-2013: Peter Dixon, University of Alberta
- 2010-2013: Randall Jamieson, University of Manitoba
- 2010-2013: Rick Dale, University of Memphis
- 2010-2013: Yana Weinstein, Washington University
- 2009-2012: Patrick Conley, University of Wisconsin
- 2009-2012: Otto MacLin, University of Northern Iowa
- 2009-2012: Douglas Mewhort, Queen's University
- 2009-2012: Danielle McNamara, University of Memphis
- 2009-2012: Kay Livesay, Linfield College
- 2009-2011: Giuseppe Riva, Universita Cattolica del Sacro Cuore
- 2008-2010: Kim-Phuong Vu, California State University
- 2008-2010: David Waller, Miami University
- 2007-2009: Michael Schulte-Mecklenbeck, University of Bern
- 2007-2009: Ping Li, Pennsylvania State University
- 2007-2009: Joseph P. Magliano, Northern Illinois University
- 2006-2008: Curt Burgess, University of California, Riverside
- 2006-2008: Katja Wiemer-Hastings, University of Memphis

### Past SCiP Executive Directors

- 2017-2019: Geoff Hollis, University of Alberta 
- 2011-2017: Rick Dale, UC Merced / UCLA
- 2006-2010: Michael Jones, Indiana University 


